import { bytesToBase64, randomToken } from "../src/crypto.ts";

const pair = await crypto.subtle.generateKey("Ed25519", true, ["sign", "verify"]) as CryptoKeyPair;
const privateKey = bytesToBase64(await crypto.subtle.exportKey("pkcs8", pair.privateKey));
const publicKey = bytesToBase64(await crypto.subtle.exportKey("spki", pair.publicKey));

const content = [
  "# Generated by deno task keygen. Keep this file out of version control.",
  "EGRYSA_CONFIG=config/egrysa.example.json",
  `EGRYSA_INBOUND_KEYS=example-workload=${randomToken(32)}`,
  `EGRYSA_RECEIPT_FINGERPRINT_KEY=${randomToken(32)}`,
  `EGRYSA_RECEIPT_ED25519_PRIVATE_KEY=${privateKey}`,
  `EGRYSA_RECEIPT_ED25519_PUBLIC_KEY=${publicKey}`,
  "OPENAI_API_KEY=",
  "ANTHROPIC_API_KEY=",
  "",
].join("\n");

const outputPath = Deno.args[0];
if (outputPath) {
  await Deno.writeTextFile(outputPath, content, { mode: 0o600 });
} else console.log(content);
