apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egrysa-receipts
  labels:
    app.kubernetes.io/name: egrysa
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
